Models/Category.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DependentDropdownPract.Models
{
    public class Category
    {
        [Key]
        public int CategoryID { get; set; }
        public string? CategoryName { get; set; }
        [NotMapped]
        public int? ProductID { get; set; }
        [NotMapped]
        public int? SubCategoryID { get; set; }

    }
}

Models/DataBaseContext.cs
using Microsoft.EntityFrameworkCore;

namespace DependentDropdownPract.Models
{
    public class DataBaseContext:DbContext
    {
        public DataBaseContext(DbContextOptions<DataBaseContext> options) : base(options) { }

        public DbSet<Category>? Category { get; set; }
        public DbSet<SubCategory>? SubCategory { get; set; }
        public DbSet<MainProduct>? MainProduct { get; set; }    


    }
}

Models/ErrorViewModel.cs
namespace DependentDropdownPract.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MainProduct.cs
using System.ComponentModel.DataAnnotations;

namespace DependentDropdownPract.Models
{
    public class MainProduct
    {
        [Key]
        public int ProductID { get; set; }
        public string? ProductName { get; set; }
        public int? SubCategoryID { get; set; }
    }
}

Models/SubCategory.cs
using System.ComponentModel.DataAnnotations;

namespace DependentDropdownPract.Models
{
    public class SubCategory
    {
        [Key]
        public int SubCategoryID { get; set; }
        public int? CategoryID { get; set; }
        public String? SubCategoryName { get; set; }
    }
}

Controllers/DemoController.cs
using DependentDropdownPract.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Storage;

namespace DependentDropdownPract.Controllers
{
    public class DemoController : Controller
    {
        private readonly DataBaseContext _context;

        public DemoController(DataBaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Category> categoryList = new();

            //getting data from db using efcore
            categoryList = (from category in _context.Category select category).ToList();

            //inserting select items in list
            categoryList.Insert(0, new Category { CategoryID = 0, CategoryName = "Select" });

            //assignign gthe categories to viewbag.listof categroy

            ViewBag.ListOfCategory = categoryList;
            return View();
        }

        public JsonResult GetSubCategory(int CategoryID)
        {
            List<SubCategory> subCategoryList = new();
            subCategoryList= (from SubCategory in _context.SubCategory where  SubCategory.CategoryID == CategoryID select SubCategory).ToList();

            subCategoryList.Insert(0, new SubCategory { SubCategoryID = 0, SubCategoryName = "Select" });

            return Json(new SelectList(subCategoryList, "SubCategoryID", "SubCategoryName"));
        }

        public JsonResult GetProducts(int  SubCategoryID)
        {
            List<MainProduct> productList = new List<MainProduct>();


            productList = (from product in _context.MainProduct where product.SubCategoryID == SubCategoryID select product).ToList();

            productList.Insert(0, new MainProduct { ProductID = 0, ProductName = "Select" });

            return Json(new SelectList(productList, "ProductID", "ProductName"));
        }


    }
}

Controllers/HomeController.cs
using DependentDropdownPract.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DependentDropdownPract.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Demo/Index.cshtml
@model DependentDropdownPract.Models.Category

@{
    <form asp-controller="Demo" asp-action="Index" method="post" class="form-horizontal" role="form">
        <div class="form-group">
            <div class="row">
                <div class="alert-danger" asp-validation-summary="ModelOnly"> </div>
                <div class="col-xs-12 col-sm-6 col-lg-4">
                    <label asp-for="CategoryName" class="control-label"></label>
                    <select id="CategoryID" name="CategoryID" class="form-control" asp-items="@(new SelectList(ViewBag.ListofCategory,"CategoryID","CategoryName"))"></select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-lg-4">
                    <label class="control-label">SubCategoryName</label>
                    <select id="SubCategoryID" name="SubCategoryID" class="form-control" asp-items="@(new SelectList(string.Empty, "SubCategoryID","SubCategoryName"))"></select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                
                <div class="col-xs-12 col-sm-6 col-lg-4">
                    <label class="control-label">Product</label>
                    <select id="ProductID" name="ProductID" class="form-control" asp-items="@(new SelectList(string.Empty,"ProductID","ProductName"))"></select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    <input id="submit1" type="submit" value="submit" />
                </div>
            </div>
        </div>
    </form>
}

<script type="text/javascript">
    $(document).ready(function () {
        var items = "<option value='0'>Select</option>";
        $('#SubCategoryID').html(items);
        $('#ProductID').html(items);

        $('#CategoryID').change(function () {
            var url = '@Url.Action("GetSubCategory", "Demo")';
            var ddlSource = "#CategoryID";
            $.getJSON(url, { CategoryID: $(ddlSource).val() }, function (data) {
                var items = "";
                $('#SubCategoryID').empty();
                $.each(data, function (i, subcategory) {
                    items += "<option value='" + subcategory.value + "'>" + subcategory.text + "</option>";
                });
                $('#SubCategoryID').html(items);
            });
        });

        $('#SubCategoryID').change(function () {
            var url = '@Url.Action("GetProducts", "Demo")';
            var ddlsource = "#SubCategoryID";
            $.getJSON(url, {
                SubCategoryID: $(ddlsource).val()
            }, function (data) {
                var items = "";
                $('#ProductID').empty();
                $.each(data, function (i, product) {
                    items += "<option value='" + product.value + "'>" + product.text + "</option>";
                });
                $('#ProductID').html(items);
            });
        });
    });
</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DependentDropdownPract</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DependentDropdownPract.styles.css" asp-append-version="true" />
    <script src="/lib/jquery/dist/jquery.js" ></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DependentDropdownPract</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DependentDropdownPract - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>